### ISSUE TITLE
careyshop v1.3.1 allows backend getshell

### ISSUE THREAD

**Issue by SZFsir** [dnyz520/careyshop#8]
In the backend, it allows the administrator to change upload file extension.
so we add PHP extension below.
![图片](https://user-images.githubusercontent.com/24249321/120919593-fdf1dd00-c6ec-11eb-8215-4f1b3100e9e5.png)

Although when it checks the mime type by file content. 
![图片](https://user-images.githubusercontent.com/24249321/120919645-43aea580-c6ed-11eb-96ac-842a91b8259e.png)

But we can use image header to bypass.
![图片](https://user-images.githubusercontent.com/24249321/120919770-dbac8f00-c6ed-11eb-84d6-f8cde3443d93.png)
![图片](https://user-images.githubusercontent.com/24249321/120919789-f848c700-c6ed-11eb-956e-f8558a0b7dce.png)

**Comment by dnyz520** [comment]
There is no conflict between the two, since PHP upload is allowed, then the upload directory should be removed from execution permissions or through OSS execution.
